### PR TITLE
Linter and page setup

### PR DESCRIPTION
**Pull request by richy4dev**
Properly set up linters, and check for errors in code.

### CODE REVIEW

**Review by omarsalem7 — CHANGES_REQUESTED** [review]
Hi @richy4dev , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

Almost near

 ## Highlights
✔️ Descriptive pull request
✔️ Descriptive commit message

 ## Required Changes ♻️

- [ ] [REQUIRED] As stated by the previous reviewer in this [PR](https://github.com/richy4dev/Hello-Microverse/pull/1) kindly make sure to set up the linter correctly and see green actions in your Pull request, you can refer to [this configuration](https://github.com/microverseinc/linters-config/tree/master/html-css).

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- [ ] [OPTIONAL] For the next time don't open a new branch for the requested changes use the same branch. 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by richy4dev** [comment]
Hello @omarsalem7, I have run checks on my code in the VS code editor, but it's not showing up here on GitHub.

**Comment by richy4dev** [comment]
merge changes to main.

**Comment by richy4dev** [comment]
Thank you all for your reviews.

**Pull request closed without merging**
